import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import LayoutPage from '@/app/components/Layout/layout-page'
import Footer from '@/app/components/Layout/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} font-anton`}>
        <div className="">
          <LayoutPage />
        </div>
        {children}
        <div className="w-full flex  flex-col overflow-hidden">
          <div className="flex flex-col h-[250px] max-lg:h-[430px] max-md:h-[600px]">
            <Footer />
          </div>
          <div className="bg-[#00FFFF] w-full justify-center flex py-2">
            <div className="text-[#000000]">
              © 2019 VIETNAMNIGHTLIFE.COM. All rights reserved
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
